###
GET http://0.0.0.0:3000/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer heyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImV4cCI6MTcwNTMzNjc2OX0.waXrHaZuV5fLsk0Xul49grKCGbnRNpJwdiOp3kpBd5w
###
POST http://0.0.0.0:3000/api/users HTTP/1.1
content-type: application/json

{
   "username":"austinwam",
   "phone":"0745456456",
   "email":"austin@gmail",
   "status":"new",
   "password":"1234567",
   "role":{
      "level":"admin",
      "permissions":[
         "all"
      ]
   }
}
###
POST http://0.0.0.0:3000/api/auth/login HTTP/1.1
content-type: application/json

{
   "email":"austin@gmail",
   "password":"1234567"
}



###